sudo: required
language: bash
services:
  - docker

matrix:
  fast_finish: true

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules

before_install:
  - docker build -t serverless-react/travis

install:
  - docker run --rm --tty --volume $TRAVIS_BUILD_DIR:/var/task --workdir /var/task serverless-react/travis yarn

script:
  - docker run --rm --tty --volume $TRAVIS_BUILD_DIR:/var/task --workdir /var/task serverless-react/travis yarn run tsc
  - docker run --rm --tty --volume $TRAVIS_BUILD_DIR:/var/task --workdir /var/task serverless-react/travis yarn run tslint
  - docker run --rm --tty --volume $TRAVIS_BUILD_DIR:/var/task --workdir /var/task serverless-react/travis yarn run build:static
  - docker run --rm --tty --volume $TRAVIS_BUILD_DIR:/var/task --workdir /var/task serverless-react/travis yarn run build:server
